---
- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:         "{{ PRI_CLU }}"
      username:         "{{ PRI_CLU_USER }}"
      password:         "{{ PRI_CLU_PASS }}"
      https:            true
      validate_certs:   false
      use_rest:         Always
  vars_files:
    - p_global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create primary SVM
    na_ontap_svm:
      state:            present
      name:             "{{ PRI_SVM }}"
      services:
        nfs:
          allowed:      true
          enabled:      true
      comment:          Created with Ansible
      <<: *input
  - name: Create management interface on primary SVM
    na_ontap_interface:
      state:                 present
      interface_name:        "{{ PRI_SVM }}"
      vserver:               "{{ PRI_SVM }}"
      address:               "{{ PRI_SVM_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_MGMT_PORT }}"
      <<: *input
      service_policy:        "default-management"
      firewall_policy:       mgmt
      role:                  data


